server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/