server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

prop:
  user:
    defaultname: userdefname

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/