server:
  port: 8921

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    webapi:
      path: /api/**
      serviceId: webapi-service

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
